import { readFileSync } from 'node:fs';

import { LAUNCH_ANIMALS } from '@kc/core';
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { describe, expect, it } from 'vitest';

import { DEFAULT_MODEL_SOCKETS } from './Avatar.js';

/**
 * Every shipped animal faces the way it runs, and carries sockets where its body actually is.
 *
 * Every generated animal used to run **tail first**. The generator builds facing Blender +Y, the
 * exporter maps that to glTF −Z, and gameplay forward is +Z (`locomotion.ts`: `(sin yaw, 0,
 * cos yaw)`; the avatar body is turned by `rotation.y = yaw`). Measured through this same loader:
 * the wolf's snout at z −0.63 and its tail reaching +1.03. Nothing caught it, because every model
 * test hashed positions, and a mesh turned round hashes the same. So this one loads the files
 * through three.js's own `GLTFLoader` — node transforms included, exactly as the game sees them —
 * and asks where the nose is.
 *
 * The socket checks exist because the generator's first attempt at them read `lib.sphere`'s size
 * as a radius when it is a diameter, and put a human's hat socket 16 cm above the top of the human.
 */

const MODELS = new URL('../../public/models/', import.meta.url);

function load(url: string): Promise<THREE.Group> {
  const bytes = readFileSync(new URL(url.replace('/models/', ''), MODELS));
  const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
  return new Promise((resolve, reject) =>
    new GLTFLoader().parse(buffer, '', (gltf) => resolve(gltf.scene), reject),
  );
}

function at(scene: THREE.Object3D, name: string): THREE.Vector3 | null {
  const node = scene.getObjectByName(name);
  return node ? node.getWorldPosition(new THREE.Vector3()) : null;
}

const generated = LAUNCH_ANIMALS.filter((a) => a.model?.credit?.startsWith('Generated by tools/blender'));

describe('every generated animal', () => {
  it('is checked at all', () => {
    // Vacuously true on an empty roster is the failure mode every scan-style guard here has had.
    expect(generated.length).toBeGreaterThanOrEqual(16);
  });

  it('faces +Z, the way it runs', async () => {
    const backwards: string[] = [];
    for (const animal of generated) {
      const scene = await load(animal.model!.url);
      scene.updateWorldMatrix(true, true);
      // The jaw runs from under the head out along the snout; the first tail joint sits at the
      // rump. Every generated rig has both, whatever its body plan.
      const snout = at(scene, 'jaw');
      const rump = at(scene, 'tail1') ?? at(scene, 'tail');
      expect(snout, `${animal.id} has no jaw bone`).not.toBeNull();
      expect(rump, `${animal.id} has no tail bone`).not.toBeNull();
      if (!(snout!.z > 0 && snout!.z > rump!.z)) {
        backwards.push(`${animal.id} (snout z ${snout!.z.toFixed(2)}, rump z ${rump!.z.toFixed(2)})`);
      }
    }
    expect(backwards, `these run tail first: ${backwards.join(', ')}`).toEqual([]);
  });

  it('carries a hat socket on its skull, not in the air and not in its neck', async () => {
    for (const animal of generated) {
      const scene = await load(animal.model!.url);
      scene.updateWorldMatrix(true, true);
      const crown = at(scene, DEFAULT_MODEL_SOCKETS.head);
      const headBone = at(scene, 'head');
      expect(crown, `${animal.id} has no ${DEFAULT_MODEL_SOCKETS.head}`).not.toBeNull();
      const top = new THREE.Box3().setFromObject(scene).max.y;
      // At or under the highest vertex — ears may rise above the skull, air may not.
      expect(crown!.y, `${animal.id} hat socket above its own model`).toBeLessThanOrEqual(top + 0.01);
      // Clearly above the joint the head pivots on, so a hat is not buried in the neck.
      expect(crown!.y - headBone!.y, `${animal.id} hat socket in the neck`).toBeGreaterThan(0.2);
    }
  });

  it('puts the face socket in front of the crown and the back socket behind or above the body', async () => {
    for (const animal of generated) {
      const scene = await load(animal.model!.url);
      scene.updateWorldMatrix(true, true);
      const crown = at(scene, DEFAULT_MODEL_SOCKETS.head)!;
      const face = at(scene, DEFAULT_MODEL_SOCKETS.face);
      const back = at(scene, DEFAULT_MODEL_SOCKETS.back);
      expect(face, `${animal.id} has no ${DEFAULT_MODEL_SOCKETS.face}`).not.toBeNull();
      expect(back, `${animal.id} has no ${DEFAULT_MODEL_SOCKETS.back}`).not.toBeNull();
      expect(face!.z, `${animal.id} glasses behind the crown`).toBeGreaterThan(crown.z + 0.1);
      expect(back!.z, `${animal.id} backpack in front of the face`).toBeLessThan(face!.z);
      // Centred: a socket off the midline is a pose baked into rest, which is how the first
      // version swayed a penguin's glasses 9 cm sideways.
      for (const [name, p] of [['head', crown], ['face', face!], ['back', back!]] as const) {
        expect(Math.abs(p.x), `${animal.id} ${name} socket off the midline`).toBeLessThan(0.01);
      }
    }
  });
});
