import { readFileSync } from 'node:fs';

import { LAUNCH_ANIMALS } from '@kc/core';
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { beforeAll, describe, expect, it } from 'vitest';

/**
 * The clips move the body the way their names say, measured through three.js's own mixer.
 *
 * Three rig defects shipped in every animal, each invisible to every test that existed, because
 * those tests hashed geometry and read node names — none of them ever played a clip:
 *
 *  - **The hop never bounced.** `Clip.key(..., loc=(0, 0, rise))` wrote "up" into the root bone's
 *    own frame, where Z is horizontal. Measured: through the whole run cycle the hips rose
 *    0.000 m and slid 0.19 m backwards at mid-hop. Every bounce, crouch, sit and backflip rise was
 *    a slide along the floor.
 *  - **Every run leaned back and every hit nodded forward.** Positive spine pitch is backwards on
 *    these rigs; the run keyed `+lean` (head 0.225 m behind idle on the kangaroo) and the hit
 *    keyed `-24` (head 0.07 m *into* the blow).
 *  - **Eyes and round ears were bound to nothing.** Heat-diffusion weighting skips small detached
 *    islands; the exporter then binds them to `neutral_bone`, so they stayed put while the head
 *    moved — 440 eye vertices on every animal, 104 ear vertices on every round-eared one.
 */

const MODELS = new URL('../../public/models/', import.meta.url);

interface Loaded {
  id: string;
  scene: THREE.Group;
  clips: THREE.AnimationClip[];
}

function load(id: string, url: string): Promise<Loaded> {
  const bytes = readFileSync(new URL(url.replace('/models/', ''), MODELS));
  const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
  return new Promise((resolve, reject) =>
    new GLTFLoader().parse(buffer, '', (gltf) => resolve({ id, scene: gltf.scene, clips: gltf.animations }), reject),
  );
}

/** World position of `node` with `clip` held at fraction `t` of its length. */
function sample(model: Loaded, clip: string, t: number, node: string): THREE.Vector3 {
  const mixer = new THREE.AnimationMixer(model.scene);
  const found = model.clips.find((c) => c.name.toLowerCase().endsWith(clip));
  if (!found) throw new Error(`${model.id} has no ${clip} clip`);
  mixer.clipAction(found).play();
  mixer.setTime(t * found.duration);
  model.scene.updateWorldMatrix(true, true);
  const position = model.scene.getObjectByName(node)!.getWorldPosition(new THREE.Vector3());
  mixer.stopAllAction();
  mixer.uncacheRoot(model.scene);
  return position;
}

const CYCLE = [0.1, 0.25, 0.4, 0.5, 0.6, 0.75, 0.9];
const generated = LAUNCH_ANIMALS.filter((a) => a.model?.credit?.startsWith('Generated by tools/blender'));
const models: Loaded[] = [];

beforeAll(async () => {
  for (const animal of generated) models.push(await load(animal.id, animal.model!.url));
});

describe('every generated animal', () => {
  it('is checked at all', () => {
    expect(models.length).toBeGreaterThanOrEqual(16);
  });

  it('binds every vertex to a real bone, not the exporter fallback', () => {
    const loose: string[] = [];
    for (const model of models) {
      let count = 0;
      model.scene.traverse((node) => {
        const mesh = node as THREE.SkinnedMesh;
        if (!mesh.isSkinnedMesh) return;
        const index = mesh.geometry.getAttribute('skinIndex');
        const weight = mesh.geometry.getAttribute('skinWeight');
        for (let v = 0; v < index.count; v++) {
          let best = 0;
          let bestWeight = -1;
          for (let k = 0; k < 4; k++) {
            if (weight.getComponent(v, k) > bestWeight) {
              bestWeight = weight.getComponent(v, k);
              best = index.getComponent(v, k);
            }
          }
          if (mesh.skeleton.bones[best]?.name === 'neutral_bone') count++;
        }
      });
      if (count) loose.push(`${model.id}: ${count}`);
    }
    expect(loose, `vertices that stay behind when the body moves: ${loose.join(', ')}`).toEqual([]);
  });

  it('bounces up through its run, not along the floor', () => {
    for (const model of models) {
      const rest = sample(model, 'idle', 0, 'hips');
      let rise = 0;
      let drift = 0;
      for (const t of CYCLE) {
        const at = sample(model, 'run', t, 'hips');
        rise = Math.max(rise, at.y - rest.y);
        drift = Math.max(drift, Math.hypot(at.x - rest.x, at.z - rest.z));
      }
      expect(rise, `${model.id} never leaves the ground in its run`).toBeGreaterThan(0.02);
      expect(drift, `${model.id} slides along the floor in its run`).toBeLessThan(0.02);
    }
  });

  it('leans into its run and reels back from a hit', () => {
    for (const model of models) {
      const idle = sample(model, 'idle', 0, 'head').z;
      const run = Math.min(...CYCLE.map((t) => sample(model, 'run', t, 'head').z)) - idle;
      const hit = Math.min(...[0.1, 0.2, 0.3].map((t) => sample(model, 'hit', t, 'head').z)) - idle;
      // Forward is +Z (see animal-orientation.test.ts). A run never carries the head behind idle.
      expect(run, `${model.id} leans back while running`).toBeGreaterThan(-0.01);
      expect(hit, `${model.id} does not recoil from a hit`).toBeLessThan(-0.02);
    }
  });
});

describe('the kangaroo', () => {
  it('stands on a tripod: its tail reaches the ground behind it', () => {
    const kangaroo = models.find((m) => m.id === 'kangaroo')!;
    kangaroo.scene.updateWorldMatrix(true, true);
    let lowest = Infinity;
    let behind = Infinity;
    kangaroo.scene.traverse((node) => {
      if (!/^tail\d$/.test(node.name)) return;
      const p = node.getWorldPosition(new THREE.Vector3());
      lowest = Math.min(lowest, p.y);
      behind = Math.min(behind, p.z);
    });
    // The generic tail stopped ~0.55 m up in mid-air, which is a wolf's tail on a kangaroo.
    expect(lowest).toBeLessThan(0.35);
    expect(behind).toBeLessThan(-0.4);
  });
});
