import * as THREE from 'three';

export interface ModelRef {
  /** URL of a .glb/.gltf file, relative to the client's public root. */
  url: string;
  scale?: number;
  /** Y offset applied after loading, so a model authored at any origin lines up with the rig. */
  offsetY?: number;
  /** Node names inside the model to use as cosmetic sockets. */
  sockets?: Partial<Record<'head' | 'face' | 'back' | 'tail' | 'handL' | 'handR', string>>;
}

/** A loaded model: a fresh scene graph plus the clips that came with it. */
export interface LoadedModel {
  scene: THREE.Object3D;
  clips: THREE.AnimationClip[];
}

/**
 * Optional art-asset layer.
 *
 * The game ships fully playable with procedural geometry; this loader lets an art pack be
 * dropped in later without touching gameplay. Rules that keep that safe:
 *
 *  - Models are **visual only**. Collision, grips and hitboxes come from level/player data, so
 *    a model swap can never change the balance of a match.
 *  - Loading is best-effort: a missing or broken file logs once and falls back to the
 *    procedural avatar rather than breaking the session.
 *  - GLTFLoader is imported dynamically, so builds with no art pack never pay for it.
 *
 * Licensing note: anything served here is downloadable by players. The models the game ships are
 * generated by `tools/blender` — original work, so the question of redistribution rights does not
 * arise. Third-party packs must be CC0, CC-BY or permissive; see docs/ASSETS.md.
 */
export class AssetLibrary {
  private cache = new Map<string, Promise<LoadedModel | null>>();
  private loader: unknown = null;
  private warned = new Set<string>();

  constructor(private readonly enabled = true) {}

  /**
   * A fresh, independently posable copy of the model, or null when unavailable.
   *
   * The copy is made with `SkeletonUtils.clone`, not `Object3D.clone`. That is not a preference:
   * `Object3D.clone` copies a `SkinnedMesh` but leaves it pointing at the *original* skeleton's
   * bones, so every clone is driven by whichever copy was posed last — sixteen players in a room
   * all move as one, or collapse into a heap at the origin. The plain clone is fine for unrigged
   * props and wrong for every character, which is exactly the case that matters here.
   */
  async load(ref: ModelRef): Promise<LoadedModel | null> {
    if (!this.enabled) return null;
    let entry = this.cache.get(ref.url);
    if (!entry) {
      entry = this.loadOnce(ref);
      this.cache.set(ref.url, entry);
    }
    const source = await entry;
    if (!source) return null;

    const { clone } = await import('three/addons/utils/SkeletonUtils.js');
    const scene = clone(source.scene);
    if (ref.scale && ref.scale !== 1) scene.scale.setScalar(ref.scale);
    if (ref.offsetY) scene.position.y += ref.offsetY;
    // Clips are immutable as far as the mixer is concerned — it reads them and writes to the
    // cloned scene — so every copy can share one set rather than duplicating the keyframe data.
    return { scene, clips: source.clips };
  }

  private async loadOnce(ref: ModelRef): Promise<LoadedModel | null> {
    try {
      const { GLTFLoader } = await import('three/addons/loaders/GLTFLoader.js');
      this.loader ??= new GLTFLoader();
      const loader = this.loader as InstanceType<typeof GLTFLoader>;
      const gltf = await loader.loadAsync(ref.url);
      const scene = gltf.scene;
      scene.traverse((node) => {
        if ((node as THREE.Mesh).isMesh) {
          node.castShadow = true;
          node.receiveShadow = true;
        }
      });
      // `gltf.animations` used to be dropped on the floor here, which made every rigged model a
      // statue and made the whole idea of an art pack pointless for characters.
      return { scene, clips: gltf.animations ?? [] };
    } catch (error) {
      if (!this.warned.has(ref.url)) {
        this.warned.add(ref.url);
        console.warn(`[assets] falling back to procedural geometry for ${ref.url}:`, (error as Error).message);
      }
      return null;
    }
  }

  /** Look up a socket node by name, for attaching cosmetics to an authored model. */
  static findSocket(root: THREE.Object3D, name: string | undefined): THREE.Object3D | null {
    if (!name) return null;
    return root.getObjectByName(name) ?? null;
  }

  /**
   * The clip whose name matches, case-insensitively and ignoring an exporter's prefixes.
   *
   * Exporters disagree about naming: Blender writes the action name, other tools prefix the
   * armature (`rig|Walk`) or the object. Matching on the tail of the name after any separator
   * means a pack does not have to be re-authored to be usable.
   */
  static findClip(clips: THREE.AnimationClip[], name: string): THREE.AnimationClip | null {
    const want = name.toLowerCase();
    for (const clip of clips) {
      const tail = clip.name.split(/[|:/]/).pop() ?? clip.name;
      if (tail.toLowerCase() === want) return clip;
    }
    for (const clip of clips) {
      if (clip.name.toLowerCase().includes(want)) return clip;
    }
    return null;
  }

  dispose(): void {
    this.cache.clear();
  }
}
