import { describe, expect, it } from 'vitest';

import { recipeFor, surfaceTextureData, texturedMaterials } from './textures.js';

/**
 * The generated surface textures.
 *
 * Tested without a DOM for the same reason the noise is: none of this needs a GPU, and the
 * properties worth protecting — that every material is covered, that the maps tile, that ice is
 * not as rough as dirt — are all numbers.
 *
 * What this replaces is not a worse texture, it is *no* texture. The game had no `TextureLoader`
 * call anywhere, so every surface was flat colour and a 124 m ice shelf was one unbroken sheet.
 */
describe('surface textures', () => {
  const SIZE = 32;

  it('covers every material the level builder can produce', () => {
    // A missing recipe silently falls back to rock, which is how the glacier would have shipped
    // with stone-coloured ice for a second time.
    const materials = texturedMaterials();
    for (const required of ['dirt', 'rock', 'wood', 'foliage', 'water', 'metal', 'sand', 'stone', 'ice', 'snow']) {
      expect(materials).toContain(required);
    }
  });

  it('produces three complete maps at the requested size', () => {
    const data = surfaceTextureData('rock', SIZE);
    expect(data.size).toBe(SIZE);
    for (const map of [data.albedo, data.normal, data.orm]) {
      expect(map.length).toBe(SIZE * SIZE * 4);
      // A fully opaque alpha everywhere: a stray zero would punch a hole in the world.
      for (let i = 3; i < map.length; i += 4) expect(map[i]).toBe(255);
    }
  });

  it('tiles every map on both axes', () => {
    /**
     * The property the whole thing rests on. A floor 124 m across repeats its texture dozens of
     * times, so a mismatch at the edge is not a subtle artefact — it is a grid drawn on the map.
     *
     * Checked on the generated bytes rather than on the noise, because the albedo, the normal and
     * the occlusion each go through their own arithmetic after the noise and any one of them could
     * break the seam on its own.
     *
     * Compared as *distributions*, which took two attempts to get right. The first version held
     * each edge pixel against one interior neighbour and failed on nearly every material — not
     * because anything was untiled, but because it ran at 32² where worley's 26 cells fall roughly
     * one per pixel, so neighbouring pixels legitimately differ enormously and a single sample says
     * nothing about what "typical" means. Normals were worst, since a gradient amplifies exactly
     * that high-frequency variation.
     *
     * If a map tiles, the column pairs across the seam are simply more adjacent pairs and their
     * mean difference should match the interior's. If it does not tile, the seam mean stands well
     * clear of it. That holds at any resolution and needs no hand-picked tolerance.
     */
    const SEAM_SIZE = 128;
    for (const material of texturedMaterials()) {
      const { albedo, normal, orm, size } = surfaceTextureData(material, SEAM_SIZE);
      for (const [name, map] of [['albedo', albedo], ['normal', normal], ['orm', orm]] as const) {
        for (const axis of ['x', 'y'] as const) {
          let interior = 0;
          let seam = 0;
          for (let k = 0; k < size; k++) {
            for (let i = 0; i < size - 1; i++) {
              const a = axis === 'x' ? (k * size + i) * 4 : (i * size + k) * 4;
              const b = axis === 'x' ? (k * size + i + 1) * 4 : ((i + 1) * size + k) * 4;
              interior += Math.abs((map[a] ?? 0) - (map[b] ?? 0));
            }
            const last = axis === 'x' ? (k * size + size - 1) * 4 : ((size - 1) * size + k) * 4;
            const first = axis === 'x' ? k * size * 4 : k * 4;
            seam += Math.abs((map[last] ?? 0) - (map[first] ?? 0));
          }
          const interiorMean = interior / (size * (size - 1));
          const seamMean = seam / size;
          expect(seamMean, `${material}/${name} seam on ${axis}`).toBeLessThanOrEqual(interiorMean * 1.6 + 1);
        }
      }
    }
  });

  it('keeps every recipe exactly periodic, however lightly a term is weighted', () => {
    /**
     * The test that actually bites, and the reason the statistical one above is not enough.
     *
     * `fbm` wraps its lattice at the octave period, which assumes its inputs span exactly one
     * tile. A recipe may stretch a pattern by scaling u or v — wood grain, brushed metal — but only
     * by a whole number; scaling by 0.37 samples a third of the tile and the edges stop meeting.
     * Four recipes shipped that mistake in the first draft.
     *
     * Mutation testing is what forced this test into existence: re-introducing a 0.37 scale on the
     * ice recipe passed the seam-distribution check, because that term carries a quarter of the
     * weight and sits under high-frequency cracks that dominate the neighbour statistics. The
     * defect is invisible in the aggregate and unmissable in the field, so the field is where it
     * gets checked — exactly, to floating point.
     */
    for (const material of texturedMaterials()) {
      const { height, stain, seed } = recipeFor(material);
      for (const t of [0, 0.13, 0.5, 0.77, 0.94]) {
        expect(height(0, t, seed), `${material} height wrap on u`).toBeCloseTo(height(1, t, seed), 10);
        expect(height(t, 0, seed), `${material} height wrap on v`).toBeCloseTo(height(t, 1, seed), 10);
        if (stain) {
          expect(stain(0, t, seed), `${material} stain wrap on u`).toBeCloseTo(stain(1, t, seed), 10);
          expect(stain(t, 0, seed), `${material} stain wrap on v`).toBeCloseTo(stain(t, 1, seed), 10);
        }
      }
    }
  });

  it('is deterministic, so every client generates the identical world', () => {
    // The same property that lets the geometry be built from a seed instead of downloaded. Two
    // players standing on the same ice must not see two different sheets of it.
    const a = surfaceTextureData('ice', SIZE);
    const b = surfaceTextureData('ice', SIZE);
    expect(Array.from(a.albedo)).toEqual(Array.from(b.albedo));
    expect(Array.from(a.normal)).toEqual(Array.from(b.normal));
    expect(Array.from(a.orm)).toEqual(Array.from(b.orm));
  });

  it('gives different materials different textures', () => {
    // A recipe table that fell back to rock for everything would pass every other test here.
    const ice = surfaceTextureData('ice', SIZE);
    const dirt = surfaceTextureData('dirt', SIZE);
    expect(Array.from(ice.albedo)).not.toEqual(Array.from(dirt.albedo));
    expect(Array.from(ice.orm)).not.toEqual(Array.from(dirt.orm));
  });

  it('keeps ice and water smoother than dirt and sand', () => {
    /**
     * Roughness is the single channel that decides whether a surface reads as wet, polished or
     * dry, and it is the one a colour-only renderer cannot express at all. If ice came out as
     * rough as dirt the glacier would look like pale concrete — which is exactly how it looked the
     * first time, when `wetRock` was reused for it.
     */
    const rough = (m: Parameters<typeof surfaceTextureData>[0]): number => {
      const { orm } = surfaceTextureData(m, SIZE);
      let sum = 0;
      for (let i = 1; i < orm.length; i += 4) sum += orm[i] ?? 0;
      return sum / (SIZE * SIZE);
    };

    expect(rough('ice')).toBeLessThan(rough('dirt'));
    expect(rough('water')).toBeLessThan(rough('ice'));
    expect(rough('sand')).toBeGreaterThan(rough('stone'));
  });

  it('darkens the occlusion where the surface is lowest', () => {
    /**
     * Ambient occlusion is a third of why a flat box reads as having depth: the creases have to be
     * darker than the ridges or the normal map is drawing a shape the shading contradicts.
     *
     * Asserted as a correlation against the height rather than as a range, because a constant AO
     * sits inside any sensible range and survives every other check here — as a mutant proved.
     */
    for (const material of ['rock', 'dirt', 'ice']) {
      const { orm, size } = surfaceTextureData(material as 'rock', SIZE);
      const { height, seed } = recipeFor(material as 'rock');

      // Banded by percentile rather than by a fixed height, because each recipe has its own
      // distribution — ridged noise is biased upward, so rock never goes below 0.35 at all and a
      // fixed threshold left the low band empty.
      const pixels: { h: number; ao: number }[] = [];
      for (let y = 0; y < size; y++) {
        for (let x = 0; x < size; x++) {
          pixels.push({ h: height(x / size, y / size, seed), ao: orm[(y * size + x) * 4] ?? 0 });
        }
      }
      pixels.sort((a, b) => a.h - b.h);
      const band = Math.floor(pixels.length / 5);
      expect(band, `${material} has pixels to band`).toBeGreaterThan(0);

      const mean = (from: number, to: number): number =>
        pixels.slice(from, to).reduce((sum, p) => sum + p.ao, 0) / (to - from);

      expect(mean(0, band), `${material} occlusion`).toBeLessThan(mean(pixels.length - band, pixels.length));
    }
  });

  it('marks metal as metal and everything else as not', () => {
    // Metalness is binary in the real world and nearly binary in a renderer: a value in the middle
    // makes a surface look like neither, which is the classic way a PBR scene goes wrong.
    expect(recipeFor('metal').metalness).toBeGreaterThan(0.8);
    for (const material of texturedMaterials()) {
      if (material === 'metal') continue;
      expect(recipeFor(material).metalness).toBeLessThan(0.2);
    }
  });

  it('builds normals that point out of the surface', () => {
    for (const material of ['ice', 'rock', 'wood']) {
      const { normal } = surfaceTextureData(material as 'ice', SIZE);
      for (let i = 2; i < normal.length; i += 4) {
        // Blue below 128 is a normal pointing into the surface, which lights the face inside out.
        expect(normal[i]).toBeGreaterThan(127);
      }
    }
  });

  it('keeps every channel inside the byte range it will be uploaded as', () => {
    // `Uint8ClampedArray` hides an out-of-range recipe by clamping it, so a material whose colour
    // plus contrast leaves 0..1 would silently flatten to pure black or white instead of failing.
    for (const material of texturedMaterials()) {
      const { albedo } = surfaceTextureData(material, SIZE);
      let saturated = 0;
      for (let i = 0; i < albedo.length; i += 4) {
        const value = albedo[i] ?? 0;
        if (value === 0 || value === 255) saturated++;
      }
      // A few clipped pixels are a highlight; a third of them is a recipe that has left the range.
      expect(saturated / (SIZE * SIZE)).toBeLessThan(0.05);
    }
  });
});
