import type { MetadataRoute } from "next";
import { publicSiteEnabled, siteUrl } from "@/lib/site";

/**
 * Read at request time, not build time.
 *
 * `PUBLIC_SITE` is a property of the deployment, and these two files are
 * statically generated by default — which meant a deploy with the site
 * switched off still served a `robots.txt` inviting crawlers in and a sitemap
 * listing pages that now answer 404. The pages themselves were gated in
 * middleware and behaved correctly, so nothing looked broken from the outside.
 */
export const dynamic = "force-dynamic";

export default function robots(): MetadataRoute.Robots {
  // With the marketing site off there is nothing here worth indexing, and an
  // indexed page for a site nobody is meant to browse is a support problem
  // rather than traffic. The sitemap is dropped too — advertising a sitemap
  // while disallowing everything is a contradiction crawlers report as an
  // error.
  if (!publicSiteEnabled()) {
    return { rules: { userAgent: "*", disallow: "/" } };
  }

  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: ["/api/"]
    },
    sitemap: `${siteUrl}/sitemap.xml`
  };
}
