import type { MetadataRoute } from "next";
import { locales } from "@/i18n/locales";
import { countries, cities } from "@/lib/countries-data";
import { guides } from "@/lib/guides-data";
import { publicSiteEnabled, siteUrl } from "@/lib/site";

const staticPaths = [
  "",
  "/dating",
  "/international-dating",
  "/how-matching-works",
  "/global-match",
  "/conversations",
  "/referral",
  "/features",
  "/pricing",
  "/safety",
  "/about",
  "/contact",
  "/guides",
  "/legal/privacy",
  "/legal/terms",
  "/legal/community-guidelines",
  "/legal/cookies",
  "/login",
  "/register"
];

const dynamicPaths = [
  ...Object.keys(countries).map((slug) => `/dating/${slug}`),
  ...Object.keys(cities).map((slug) => `/dating/${slug}`),
  ...Object.keys(guides).map((slug) => `/guides/${slug}`)
];

/**
 * Read at request time, not build time.
 *
 * `PUBLIC_SITE` is a property of the deployment, and these two files are
 * statically generated by default — which meant a deploy with the site
 * switched off still served a `robots.txt` inviting crawlers in and a sitemap
 * listing pages that now answer 404. The pages themselves were gated in
 * middleware and behaved correctly, so nothing looked broken from the outside.
 */
export const dynamic = "force-dynamic";

export default function sitemap(): MetadataRoute.Sitemap {
  // Nothing is crawlable with the marketing site off, so the sitemap is empty
  // rather than listing pages that answer 404 — a sitemap full of dead URLs is
  // a signal Search Console reports as an error against the domain.
  if (!publicSiteEnabled()) return [];

  const allPaths = [...staticPaths, ...dynamicPaths];

  return allPaths.flatMap((path) =>
    locales.map((locale) => ({
      url: `${siteUrl}/${locale}${path}`,
      lastModified: new Date(),
      alternates: {
        languages: Object.fromEntries(locales.map((l) => [l, `${siteUrl}/${l}${path}`]))
      }
    }))
  );
}
