/**
 * Dump the animal roster to JSON for the Blender model generator.
 *
 * The generator needs each animal's colours, proportions and body plan. Those already exist, in
 * `LAUNCH_ANIMALS` — so they are read from there rather than retyped in Python. A second copy of
 * "the kangaroo is 0xc98a52 with tall ears and a thick tail" is a copy that will disagree with the
 * game the first time someone recolours an animal and changes only one of them.
 *
 * The capsule the models have to fit is taken from the same place the simulation takes it, for the
 * same reason: a model authored against a guessed height floats or sinks.
 *
 * Usage: npm run assets:spec
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { LAUNCH_ANIMALS, DEFAULT_MOVEMENT } from '@kc/core';

const out = resolve('tools/blender/animals.json');

const spec = {
  $comment:
    'GENERATED by scripts/dump-animal-specs.ts — do not edit. Run `npm run assets:spec` to refresh.',
  capsule: {
    radius: DEFAULT_MOVEMENT.radius,
    standHeight: DEFAULT_MOVEMENT.standHeight,
    crouchHeight: DEFAULT_MOVEMENT.crouchHeight,
    headHeightRatio: DEFAULT_MOVEMENT.headHeightRatio,
  },
  animals: LAUNCH_ANIMALS.map((a) => ({
    id: a.id,
    name: a.name,
    visual: a.visual,
    // Where the client will look for the file, so the generator writes to the path the game reads.
    modelUrl: a.model?.url ?? `/models/${a.id}.glb`,
  })),
};

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `${JSON.stringify(spec, null, 2)}\n`);
console.log(`animal spec → ${out} (${spec.animals.length} animals)`);
