"""
Shared Blender helpers for generating the game's art.

Why the art is generated by a script rather than downloaded or drawn by hand:

  * **Licence.** The game is web-delivered, so every file the server sends can be pulled out of
    the browser by any player. That makes "may end users extract the raw asset?" a question we
    cannot answer with "no", and it is the reason `assets/packs.json` refuses anything but CC0,
    CC-BY and permissive sources. Geometry produced by this script is original work, so the
    question does not arise at all.
  * **Reproducibility.** A binary in a repository with no source is a dead end — nobody can fix a
    proportion or recolour a body six months later. Every model here is a seeded function of the
    game's own data, so regenerating is `npm run assets:build` and the diff is reviewable.
  * **It cannot drift from the game.** Colours, proportions and body plans are read from
    `tools/blender/animals.json`, which is dumped straight out of `LAUNCH_ANIMALS`. Recolouring
    an animal in the game data recolours the model; there is no second copy to forget.

Conventions, which matter because getting them wrong is invisible until the model is in a match:

  * **Units are metres**, matching the simulation.
  * **Origin at the feet.** `MovementConfig.position` is the point the feet stand on, so a model
    centred on its body floats or sinks by half its height.
  * **Forward is +Y in Blender.** The glTF exporter maps Blender's Z-up to glTF's Y-up, sending
    Blender +Y to glTF -Z — which is the direction three.js treats as forward. Build facing +Y
    and the character faces where it walks.
  * **Flat shading, no textures.** Colour comes from per-material base colour, which keeps files
    in the low tens of kilobytes and matches the chunky low-poly look the rest of the art uses.
    A texture would be the single biggest thing in the download budget.
"""

import math
import os

import bpy
from mathutils import Euler, Matrix, Quaternion, Vector

# --------------------------------------------------------------------------------------------
# Scene
# --------------------------------------------------------------------------------------------


def reset() -> None:
    """An empty scene with nothing inherited from a previous build in it."""
    bpy.ops.wm.read_factory_settings(use_empty=True)
    # Actions survive a factory reset when they carry a fake user, and a stale action from a
    # previous animal would be exported into the next one's file as a bonus animation.
    for block in (bpy.data.actions, bpy.data.materials, bpy.data.meshes, bpy.data.armatures):
        for item in list(block):
            block.remove(item)


def hex_to_linear(value: int) -> tuple:
    """
    A game-data colour (0xRRGGBB) as Blender's linear RGBA.

    The conversion is not decoration. Blender works in linear space and glTF stores base colour
    in sRGB; handing a raw 0..1 sRGB value straight to a material makes every model come out
    visibly washed out against the UI colours taken from the same hex.
    """
    srgb = ((value >> 16) & 0xFF) / 255.0, ((value >> 8) & 0xFF) / 255.0, (value & 0xFF) / 255.0

    def to_linear(c: float) -> float:
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

    return (to_linear(srgb[0]), to_linear(srgb[1]), to_linear(srgb[2]), 1.0)


_materials: dict = {}


def material(name: str, hex_colour: int, roughness: float = 0.75) -> bpy.types.Material:
    """A flat solid-colour material, created once per name."""
    key = (name, hex_colour)
    if key in _materials:
        return _materials[key]
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    bsdf.inputs["Base Color"].default_value = hex_to_linear(hex_colour)
    bsdf.inputs["Roughness"].default_value = roughness
    # Metallic stays at zero: a stylised animal that catches specular highlights like a car reads
    # as plastic, and every glTF viewer defaults metallic to 1.0 if the input is left unset.
    bsdf.inputs["Metallic"].default_value = 0.0
    _materials[key] = mat
    return mat


def reset_materials() -> None:
    _materials.clear()


# --------------------------------------------------------------------------------------------
# Primitives
# --------------------------------------------------------------------------------------------


def box(name, center, size, mat, rotation=(0.0, 0.0, 0.0)):
    """An axis-aligned box. `size` is full width/depth/height, not half-extents."""
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=center)
    ob = bpy.context.active_object
    ob.name = name
    ob.scale = (size[0], size[1], size[2])
    ob.rotation_euler = Euler(rotation, "XYZ")
    _finish(ob, mat)
    return ob


def sphere(name, center, size, mat, segments=10, rings=6, rotation=(0.0, 0.0, 0.0)):
    """
    A low-polygon UV sphere, scaled per axis so one call covers heads, bellies and berries.

    Deliberately coarse: at 10x6 a sphere is 108 triangles, which reads as a rounded form at
    gameplay distance and costs a twentieth of what Blender's default would.
    """
    bpy.ops.mesh.primitive_uv_sphere_add(segments=segments, ring_count=rings, radius=0.5, location=center)
    ob = bpy.context.active_object
    ob.name = name
    ob.scale = (size[0], size[1], size[2])
    # Optional so every existing call keeps its geometry bit-for-bit. A limb or a tail segment
    # running along a diagonal needs its long axis along that diagonal: an axis-aligned ellipsoid
    # laid on a slope reads as a flat disc, and a chain of them reads as loose lumps.
    ob.rotation_euler = Euler(rotation, "XYZ")
    _finish(ob, mat)
    return ob


def cone(name, center, radius1, radius2, depth, mat, vertices=8, rotation=(0.0, 0.0, 0.0)):
    """A truncated cone — ears, snouts, tails, tree trunks."""
    bpy.ops.mesh.primitive_cone_add(
        vertices=vertices, radius1=radius1, radius2=radius2, depth=depth, location=center
    )
    ob = bpy.context.active_object
    ob.name = name
    ob.rotation_euler = Euler(rotation, "XYZ")
    _finish(ob, mat)
    return ob


def wedge(name, center, size, mat, rotation=(0.0, 0.0, 0.0)):
    """
    A fin: a right triangle standing in the YZ plane, extruded `size[0]` thick along X.

    The base runs along the bottom the full depth `size[1]`, and the apex sits above the *back*
    end, so the leading edge sweeps back the way a dorsal fin, a tail fluke or a shark's ear does.
    Fins used to be boxes, and from the side a shark read as three dark squares.

    Faces are wound outward on purpose: `hidden_parts` and `detached_parts` treat every part as a
    convex solid bounded by its face planes, so a reversed face would put the inside outside.
    """
    w, d, h = size[0] / 2, size[1] / 2, size[2] / 2
    verts = [(-w, d, -h), (-w, -d, -h), (-w, -d, h), (w, d, -h), (w, -d, -h), (w, -d, h)]
    # left (-X), right (+X), bottom (-Z), back (-Y), leading edge (+Y+Z)
    faces = [(0, 1, 2), (3, 5, 4), (0, 3, 4, 1), (1, 4, 5, 2), (0, 2, 5, 3)]
    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata(verts, [], faces)
    mesh.update()
    ob = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(ob)
    ob.location = center
    ob.rotation_euler = Euler(rotation, "XYZ")
    _finish(ob, mat)
    return ob


def _finish(ob, mat) -> None:
    ob.data.materials.append(mat)
    for poly in ob.data.polygons:
        poly.use_smooth = False


def join(parts, name):
    """
    One mesh from many primitives.

    Joining before skinning is what makes automatic weights usable: separate objects each get
    their own armature modifier and their own weight solve, and the seams between them tear open
    the moment a bone rotates.
    """
    parts = [p for p in parts if p is not None]
    bpy.ops.object.select_all(action="DESELECT")
    for p in parts:
        p.select_set(True)
    bpy.context.view_layer.objects.active = parts[0]
    bpy.ops.object.join()
    ob = bpy.context.active_object
    ob.name = name
    # Scale and rotation are baked in now, while the mesh is still unskinned. Leaving a non-unit
    # scale on the object makes the armature deform in the wrong space and is close to impossible
    # to diagnose from the result.
    bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
    return ob


def join_into(target, parts):
    """
    Join `parts` into an existing mesh, which keeps its own modifiers, parent and vertex groups.

    For pinned parts after skinning: see `characters.skin_parts`.
    """
    parts = [p for p in parts if p is not None]
    if not parts:
        return target
    bpy.ops.object.select_all(action="DESELECT")
    target.select_set(True)
    for p in parts:
        p.select_set(True)
    bpy.context.view_layer.objects.active = target
    bpy.ops.object.join()
    return target


def is_pinned(ob) -> bool:
    return any(g.name.startswith(PIN_PREFIX) for g in ob.vertex_groups)


def triangle_count(ob) -> int:
    ob.data.calc_loop_triangles()
    return len(ob.data.loop_triangles)


# --------------------------------------------------------------------------------------------
# Rig
# --------------------------------------------------------------------------------------------


def armature(name, bones):
    """
    Build an armature from `(bone_name, head, tail, parent_or_None)` tuples, in order.

    Parents must appear before their children, which is checked rather than assumed: a bone whose
    parent is missing is silently rooted at the origin, and the result is a limb that swings from
    the middle of the world.
    """
    arm_data = bpy.data.armatures.new(name)
    arm_obj = bpy.data.objects.new(name, arm_data)
    bpy.context.scene.collection.objects.link(arm_obj)
    bpy.context.view_layer.objects.active = arm_obj
    bpy.ops.object.mode_set(mode="EDIT")

    made = set()
    for bone_name, head, tail, parent in bones:
        if parent is not None and parent not in made:
            raise ValueError(f"bone {bone_name!r} names parent {parent!r} before it exists")
        eb = arm_data.edit_bones.new(bone_name)
        eb.head = Vector(head)
        eb.tail = Vector(tail)
        if (eb.tail - eb.head).length < 1e-4:
            raise ValueError(f"bone {bone_name!r} has zero length; Blender would drop it")
        if parent is not None:
            eb.parent = arm_data.edit_bones[parent]
        made.add(bone_name)

    bpy.ops.object.mode_set(mode="OBJECT")
    return arm_obj


def bone_socket(arm_obj, bone_name: str, name: str, world_pos) -> "bpy.types.Object":
    """
    An empty parented to a bone, placed at a world position, exported as a named glTF node.

    This is how a model tells the renderer where a hat goes. It rides the bone, so a hat follows
    the head through every clip, and it is placed in *world* space after parenting, because a
    bone-parented object's local frame starts at the bone's tail and points along the bone — a
    literal offset would mean something different on every body plan.
    """
    if bone_name not in arm_obj.data.bones:
        raise KeyError(f"socket {name!r} names bone {bone_name!r}, which this rig does not have")
    empty = bpy.data.objects.new(name, None)
    bpy.context.scene.collection.objects.link(empty)
    empty.empty_display_size = 0.05
    empty.parent = arm_obj
    empty.parent_type = "BONE"
    empty.parent_bone = bone_name
    bpy.context.view_layer.update()
    empty.matrix_world = Matrix.Translation(Vector(world_pos))
    bpy.context.view_layer.update()
    return empty


def skin(mesh_obj, arm_obj) -> None:
    """Bind mesh to armature with automatic (heat-diffusion) weights."""
    bpy.ops.object.select_all(action="DESELECT")
    mesh_obj.select_set(True)
    arm_obj.select_set(True)
    bpy.context.view_layer.objects.active = arm_obj
    bpy.ops.object.parent_set(type="ARMATURE_AUTO")
    if not any(m.type == "ARMATURE" for m in mesh_obj.modifiers):
        raise RuntimeError(f"{mesh_obj.name} did not receive an armature modifier")


def _convex_solids(parts):
    """Each part as (name, world vertices, outward face normals, plane offsets)."""
    import numpy as np

    bpy.context.view_layer.update()
    solids = []
    for p in parts:
        mw = p.matrix_world
        verts = np.array([tuple(mw @ v.co) for v in p.data.vertices])
        normals, offsets = [], []
        for f in p.data.polygons:
            a = mw @ p.data.vertices[f.vertices[0]].co
            b = mw @ p.data.vertices[f.vertices[1]].co
            c = mw @ p.data.vertices[f.vertices[2]].co
            n = (b - a).cross(c - a)
            if n.length < 1e-12:
                continue
            n.normalize()
            normals.append(tuple(n))
            offsets.append(n.dot(a))
        solids.append((p.name, verts, np.array(normals), np.array(offsets)))
    return solids


def detached_parts(parts, reach: float = 0.01) -> list:
    """
    Parts that touch no other part: a tail, an ear or a hand floating free of the body.

    Measured by rendering, not by reading: every waddler's stub tail hung twelve centimetres
    behind the body, because the egg narrows at hip height and the tail was placed against the
    widest part of it. Nothing about the numbers looked wrong. A part is attached when any of its
    vertices lies within `reach` of the inside of another part, or another part's vertex lies
    within `reach` of the inside of it — the same exact convex test as `hidden_parts`, loosened
    by a centimetre so that two parts meeting face to face count as touching.
    """
    import numpy as np

    solids = _convex_solids(parts)
    touching = {name: False for name, *_ in solids}
    for i, (name, verts, _n, _d) in enumerate(solids):
        for j, (other, _v, normals, offsets) in enumerate(solids):
            if i == j or len(normals) == 0:
                continue
            if np.any(np.all(verts @ normals.T - offsets < reach, axis=1)):
                touching[name] = touching[other] = True
    return [name for name, ok in touching.items() if not ok]


def hidden_parts(parts, threshold: float = 0.97) -> list:
    """
    Parts whose vertices lie almost entirely inside other parts, as `(name, fraction)` pairs.

    Such a part draws nothing, and it is not merely waste: a closed island no bone can see gives
    heat-diffusion weighting a singular block. A draft of the upright plan had one — a neck
    enclosed by the shoulders and the skull on all seven upright animals — and the solve then
    failed or not on floating-point summation order, 3 skins in 320, each time leaving over a
    thousand vertices on no bone at all. On the shipped plans the most-hidden part is 83 % hidden
    (a belly set into a torso), so the default threshold leaves a real margin.

    Exact rather than approximate, because every part this generator builds is convex (spheres,
    boxes, cones, and affine images of them): a point is inside a convex solid exactly when it is
    behind every one of its face planes. A first version compared against the nearest face's normal
    and reported whole eyes as hidden on one side of a head and not the other — wrong at edges,
    where the nearest face is not the face the point is behind.
    """
    import numpy as np

    solids = _convex_solids(parts)
    hidden = []
    for name, verts, _n, _d in solids:
        inside = np.zeros(len(verts), dtype=bool)
        for other, _v, normals, offsets in solids:
            if other == name or len(normals) == 0:
                continue
            # Behind every plane by a millimetre: touching a surface is not being hidden by it.
            inside |= np.all(verts @ normals.T - offsets < -1e-3, axis=1)
        fraction = float(inside.mean()) if len(verts) else 0.0
        if fraction >= threshold:
            hidden.append((name, round(fraction, 3)))
    return hidden


PIN_PREFIX = "pin:"


def pin(ob, bone_name: str):
    """
    Mark a part, before `join`, as riding one bone rigidly.

    Stored as a vertex group named `pin:<bone>`, which survives joining (groups merge by name) and
    automatic weighting (which only writes groups named after bones). `apply_pins` turns it into
    a full weight on that bone afterwards.
    """
    group = ob.vertex_groups.new(name=PIN_PREFIX + bone_name)
    group.add([v.index for v in ob.data.vertices], 1.0, "REPLACE")
    return ob


def apply_pins(mesh_obj) -> int:
    """Give every pinned vertex a single full weight on its bone, and drop the pin groups."""
    moved = 0
    for pin_group in [g for g in mesh_obj.vertex_groups if g.name.startswith(PIN_PREFIX)]:
        bone_name = pin_group.name[len(PIN_PREFIX):]
        target = mesh_obj.vertex_groups.get(bone_name) or mesh_obj.vertex_groups.new(name=bone_name)
        members = [v.index for v in mesh_obj.data.vertices if any(g.group == pin_group.index for g in v.groups)]
        for vi in members:
            for g in list(mesh_obj.data.vertices[vi].groups):
                if g.group not in (target.index, pin_group.index):
                    mesh_obj.vertex_groups[g.group].remove([vi])
        target.add(members, 1.0, "REPLACE")
        mesh_obj.vertex_groups.remove(pin_group)
        moved += len(members)
    return moved


def unweighted_vertices(mesh_obj) -> int:
    """Vertices with no bone weight at all — each one is bound to the exporter's `neutral_bone`."""
    bone_groups = {g.index for g in mesh_obj.vertex_groups if not g.name.startswith(PIN_PREFIX)}
    return sum(1 for v in mesh_obj.data.vertices if not any(g.group in bone_groups and g.weight > 1e-4 for g in v.groups))


# --------------------------------------------------------------------------------------------
# Animation
# --------------------------------------------------------------------------------------------


class Clip:
    """
    One named animation.

    Keys are written as Euler-derived quaternions because posing in degrees is what the animal
    definitions read like, while quaternions are what glTF stores and what interpolates without
    gimbal surprises halfway through a stride.
    """

    def __init__(self, arm_obj, name: str, length: int):
        self.arm = arm_obj
        self.name = name
        self.length = length
        if arm_obj.animation_data is None:
            arm_obj.animation_data_create()
        self.action = bpy.data.actions.new(name)
        # Without a fake user the action is unused the moment the next one is assigned, and an
        # unused action is not exported — the file comes out with only the last clip in it.
        self.action.use_fake_user = True
        arm_obj.animation_data.action = self.action
        slots = getattr(self.action, "slots", None)
        if slots is not None and getattr(arm_obj.animation_data, "action_slot", None) is None and len(slots):
            arm_obj.animation_data.action_slot = slots[0]

    def key(self, bone: str, frame: int, rot_deg=(0.0, 0.0, 0.0), loc=None) -> None:
        pb = self.arm.pose.bones.get(bone)
        if pb is None:
            raise KeyError(f"no bone {bone!r} to key in clip {self.name!r}")
        pb.rotation_mode = "QUATERNION"
        pb.rotation_quaternion = Euler([math.radians(a) for a in rot_deg], "XYZ").to_quaternion()
        pb.keyframe_insert("rotation_quaternion", frame=frame)
        if loc is not None:
            # `loc` is an armature-space offset — x right, y forward, z up — because that is how
            # every call site writes it: `loc=(0, 0, rise)` means "up". A pose bone's location is
            # in the bone's *own* rest frame, though, and the root bone points up, so its local Z
            # is horizontal. Measured through the real clips before this conversion: the hips
            # moved 0.000 m up through the whole run cycle and slid 0.19 m backwards at mid-hop.
            # Every bounce, crouch, sit and backflip rise in the game was a slide along the floor.
            rest = self.arm.data.bones[bone].matrix_local.to_3x3()
            pb.location = rest.inverted() @ Vector(loc)
            pb.keyframe_insert("location", frame=frame)

    def cycle(self, bone: str, keys) -> None:
        """
        Key a looping channel, repeating frame 1's pose on the last frame.

        A walk whose first and last frames differ pops once per stride. It is the single most
        common way a procedural cycle looks wrong, and the fix is mechanical, so it is done here
        rather than left to each caller to remember.
        """
        for frame, rot in keys:
            self.key(bone, frame, rot)
        first = keys[0][1]
        self.key(bone, self.length, first)


# --------------------------------------------------------------------------------------------
# Export
# --------------------------------------------------------------------------------------------


def export_glb(path: str, animated: bool = True, normals: bool = True, uvs: bool = True) -> int:
    """
    Write the whole scene to a .glb and return its size in bytes.

    `normals=False` is not a downgrade, it is the cheaper way to get the same picture. Flat shading
    forces the exporter to split every shared vertex so each face can carry its own normal, which
    on a rock costs more than the geometry does — 125 KB against 48 KB for the same 1247 triangles.
    The glTF spec says a renderer must compute flat normals when the attribute is absent, and
    three.js does exactly that: `GLTFLoader` sets `flatShading` when `geometry.attributes.normal`
    is undefined. So dropping them gives the identical faceted look for a third of the bytes, and
    needs nothing on the client side to arrange it.

    Skinned characters keep theirs: their normals have to follow the bones, and the saving there is
    a much smaller share of a file that is mostly animation.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)
    bpy.ops.export_scene.gltf(
        filepath=path,
        export_format="GLB",
        export_normals=normals,
        # Exactly one colour layer. The defaults are `export_all_vertex_colors=True` *and*
        # `export_active_vertex_color_when_no_material=True`, and together they write the same
        # attribute out twice — as COLOR_0 and again as COLOR_1. three.js reads COLOR_0 and
        # ignores the rest, so the duplicate was pure weight in every prop.
        export_vertex_color="ACTIVE",
        export_all_vertex_colors=False,
        # No prop or animal carries a texture — colour is per-material — so texture coordinates
        # are bytes describing where to sample an image that does not exist.
        export_texcoords=uvs,
        export_animations=animated,
        export_animation_mode="ACTIONS",
        # Sampling every frame makes a procedurally keyed cycle survive the trip intact; glTF has
        # no notion of Blender's interpolation curves, so an unsampled export can arrive linear
        # where it was meant to ease.
        export_force_sampling=animated,
        export_apply=True,
        export_yup=True,
        export_cameras=False,
        export_lights=False,
    )
    return os.path.getsize(path)


def scene_triangles() -> int:
    total = 0
    for ob in bpy.context.scene.objects:
        if ob.type == "MESH":
            total += triangle_count(ob)
    return total
