import { useEffect, useMemo, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { ArrowDown, ArrowRight, Camera, Download, Menu, Mountain, Play, Send, Video, X } from 'lucide-react'
import './App.css'

const images = {
  hero: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=2200&q=85',
  valley: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1800&q=82',
  forest: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1400&q=82',
  lake: 'https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&w=1400&q=82',
  concept: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1800&q=82',
}
const imageNote = 'Editorial reference image · Unsplash source · not a photograph of the project'
const phases = [
  ['01', 'Idea', 'A place imagined in conversation with the landscape.', 'complete'],
  ['02', 'Planning', 'Understanding the land, context and what is possible.', 'current'],
  ['03', 'Design', 'Exploring an underground architecture rooted in place.', 'next'],
  ['04', 'Preparation', 'The work that must happen before anything is built.', 'future'],
  ['05', 'Construction', 'When the first stone is placed, we will show it here.', 'future'],
  ['06', 'Interior', 'Making the spaces warm, quiet and connected to the sky.', 'future'],
  ['07', 'Opening', 'One day, welcoming the first guests to Trevelin.', 'future'],
] as const
const pageMeta: Record<string, [string, string]> = {
  '/': ['Patagonia Underground — Trevelin, Patagonia', 'A unique project taking shape in Trevelin, Chubut, Argentina. Follow the real journey from the beginning.'],
  '/project': ['The Project — Patagonia Underground', 'Discover the purpose, architectural idea and future accommodation concept behind Patagonia Underground.'],
  '/transparency': ['Project Transparency — Patagonia Underground', 'See the current stage and future phases of Patagonia Underground without fake progress.'],
  '/journal': ['Construction Journal — Patagonia Underground', 'A construction journal that will begin when work on the first phase starts.'],
  '/gallery': ['Gallery — Trevelin and Patagonia Underground', 'Explore Trevelin landscapes and clearly labelled project concept references.'],
  '/progress': ['Follow the Journey — Patagonia Underground', 'Follow every real phase from idea and planning to a possible future opening.'],
  '/story': ['Our Story — Patagonia Underground', 'The idea, place, vision and building-in-public principles behind Patagonia Underground.'],
  '/location': ['Trevelin, Chubut — Patagonia Underground', 'Learn about the natural setting of Trevelin without invented coordinates or travel claims.'],
  '/updates': ['Project Updates — Patagonia Underground', 'Real project updates will be published here as the journey develops.'],
}

type Member = { firstName: string; email: string; country: string; consent: boolean; createdAt: string; status: 'active' | 'inactive' }
const getMembers = (): Member[] => { try { const value = JSON.parse(localStorage.getItem('patagonia-community') || '[]'); return Array.isArray(value) ? value : [] } catch { return [] } }
const saveMembers = (members: Member[]) => localStorage.setItem('patagonia-community', JSON.stringify(members))

function App() {
  const [path, setPath] = useState(window.location.pathname.replace(/\/$/, '') || '/')
  const [menuOpen, setMenuOpen] = useState(false)
  const [adminOpen, setAdminOpen] = useState(false)
  const [members, setMembers] = useState<Member[]>(getMembers)
  const [formMessage, setFormMessage] = useState('')
  const navigate = (to: string) => { window.history.pushState({}, '', to); setPath(to.split('#')[0] || '/'); setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }); if (to.includes('#community')) window.setTimeout(() => document.getElementById('community')?.scrollIntoView({ behavior: 'smooth' }), 0) }
  useEffect(() => { const onPop = () => setPath(window.location.pathname.replace(/\/$/, '') || '/'); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop) }, [])
  useEffect(() => { const [title, description] = pageMeta[path] || ['Page not found — Patagonia Underground', 'The requested Patagonia Underground page could not be found.']; document.title = title; let meta = document.querySelector('meta[name="description"]'); if (!meta) { meta = document.createElement('meta'); meta.setAttribute('name', 'description'); document.head.appendChild(meta) }; meta.setAttribute('content', description); const canonical = document.querySelector('link[rel="canonical"]'); canonical?.setAttribute('href', `${window.location.origin}${path === '/' ? '/' : path}`) }, [path])
  const join = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const firstName = String(data.get('firstName') || '').trim().slice(0, 80); const email = String(data.get('email') || '').trim().toLowerCase().slice(0, 160); const country = String(data.get('country') || '').trim().slice(0, 80); if (!firstName || !email || data.get('consent') !== 'on') return; const current = getMembers(); if (current.some(member => member.email.toLowerCase() === email)) { setFormMessage('This email is already on the journey list.'); return } const updated = [...current, { firstName, email, country, consent: true, createdAt: new Date().toISOString(), status: 'active' as const }]; saveMembers(updated); setMembers(updated); event.currentTarget.reset(); setFormMessage("You're in. We'll keep you updated as Patagonia Underground takes shape."); }
  return <div className="site-shell"><Header path={path} navigate={navigate} menuOpen={menuOpen} setMenuOpen={setMenuOpen} /><main>{path === '/' ? <Home navigate={navigate} join={join} formMessage={formMessage} /> : <Page path={path} navigate={navigate} join={join} formMessage={formMessage} />}</main><Footer navigate={navigate} setAdminOpen={setAdminOpen} />{adminOpen && <Admin members={members} setMembers={setMembers} close={() => setAdminOpen(false)} />}</div>
}

function Header({ path, navigate, menuOpen, setMenuOpen }: { path: string; navigate: (to: string) => void; menuOpen: boolean; setMenuOpen: (value: boolean) => void }) { return <header className="topbar"><button className="wordmark" onClick={() => navigate('/')} aria-label="Patagonia Underground home"><span>PATAGONIA</span><strong>UNDERGROUND</strong></button><nav className={menuOpen ? 'nav open' : 'nav'} aria-label="Main navigation">{[['/project', 'Project'], ['/story', 'Our story'], ['/transparency', 'Transparency'], ['/gallery', 'Gallery'], ['/location', 'Location']].map(([href, label]) => <button className={path === href ? 'active' : ''} key={href} onClick={() => navigate(href)}>{label}</button>)}<button className="nav-join" onClick={() => navigate('/#community')}>Join the journey <ArrowRight size={14} /></button></nav><button className="menu-btn" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu" aria-expanded={menuOpen}>{menuOpen ? <X /> : <Menu />}</button></header> }

function Home({ navigate, join, formMessage }: { navigate: (to: string) => void; join: (event: FormEvent<HTMLFormElement>) => void; formMessage: string }) { return <>
  <section className="hero"><img src={images.hero} alt="Mountain valley landscape used as a Trevelin editorial reference" fetchPriority="high" /><div className="hero-shade" /><div className="hero-topline"><span>Trevelin · Chubut · Patagonia · Argentina</span><span className="mono">EST. / IN THE MAKING</span></div><div className="hero-content"><p className="eyebrow">A future place beneath the wild landscape</p><h1>Patagonia<br /><em>Underground</em></h1><p className="hero-copy">A unique project taking shape in Patagonia. Rooted in the earth, open to the sky, and shared from the very beginning.</p><div className="hero-actions"><button className="button light" onClick={() => navigate('/project')}>Discover the project <ArrowDown size={16} /></button><button className="text-link" onClick={() => document.getElementById('community')?.scrollIntoView({ behavior: 'smooth' })}>Join the journey <ArrowRight size={16} /></button></div></div><div className="hero-footer"><span>SCROLL TO EXPLORE</span><span className="scroll-line" /><span>01 / 07</span></div></section>
  <section className="intro section-pad"><SectionLabel number="01" text="Welcome to Trevelin" /><div className="intro-grid"><div><h2>Where the valley<br /><em>holds the silence.</em></h2></div><div className="intro-copy"><p className="lead">Trevelin is a small town in Chubut, where green valleys meet the Andes and every season changes the way the light falls.</p><p>Patagonia Underground is an early-stage architectural project inspired by this relationship: earth, stone, sky and the simple luxury of feeling somewhere completely.</p><button className="arrow-link" onClick={() => navigate('/story')}>Read our story <ArrowRight size={17} /></button></div></div></section>
  <section className="wide-image"><img src={images.valley} alt="Patagonian valley and mountains, editorial reference" loading="lazy" /><div className="image-caption"><span>THE LANDSCAPE IS NOT A BACKDROP</span><strong>It is the beginning.</strong></div></section>
  <section className="story section-pad"><SectionLabel number="02" text="Building in public" /><div className="story-grid"><div className="story-heading"><p className="eyebrow">Our story</p><h2>A project that starts<br /><em>with a question.</em></h2><p>What would it feel like to stay beneath the landscape, without ever leaving it?</p></div><StoryList /></div></section>
  <section className="concept section-pad"><div className="concept-image"><img src={images.concept} alt="Warm stone and timber interior concept reference, not built" loading="lazy" /><span className="image-tag">CONCEPT REFERENCE · NOT BUILT</span></div><div className="concept-copy"><SectionLabel number="03" text="The architectural idea" /><h2>Under the earth.<br /><em>Open to the stars.</em></h2><p>The visual direction explores stone, timber, planted roofs and a central opening to the Patagonian sky. These images communicate an idea only; they are not photographs of a completed project.</p><div className="material-row"><span>Stone</span><span>Earth</span><span>Timber</span><span>Sky</span></div></div></section>
  <TransparencyBlock navigate={navigate} />
  <section className="journal section-pad"><div className="journal-card"><div><SectionLabel number="05" text="Construction journal" /><h2>The journal will<br /><em>begin on site.</em></h2><p>The construction journal will begin when the first phase of the project starts. Until then, this space stays intentionally quiet.</p></div><div className="journal-status"><span className="status-dot" /> No construction updates yet</div></div></section>
  <Community join={join} formMessage={formMessage} />
  </> }

function Page({ path, navigate, join, formMessage }: { path: string; navigate: (to: string) => void; join: (event: FormEvent<HTMLFormElement>) => void; formMessage: string }) { const content: Record<string, ReactNode> = { '/project': <Project navigate={navigate} />, '/story': <StoryPage />, '/transparency': <TransparencyPage navigate={navigate} />, '/progress': <ProgressPage />, '/journal': <JournalPage />, '/gallery': <GalleryPage />, '/location': <LocationPage />, '/updates': <UpdatesPage />, '/community': <Community join={join} formMessage={formMessage} /> }; return content[path] || <NotFound navigate={navigate} /> }
function SectionLabel({ number, text }: { number: string; text: string }) { return <div className="section-label">{number} <span>{text}</span></div> }
function StoryList() { return <div className="story-list"><article><span>01</span><div><h3>The idea</h3><p>A circular, earth-sheltered retreat imagined for quiet stays and long views. This is a concept in development, not a completed building.</p></div></article><article><span>02</span><div><h3>Why Patagonia?</h3><p>Because Trevelin offers a living landscape where mountain, forest, water and weather remain the main characters.</p></div></article><article><span>03</span><div><h3>The future</h3><p>One day, the project may become a future accommodation experience. For now, the honest story is the journey toward that possibility.</p></div></article></div> }
function Project({ navigate }: { navigate: (to: string) => void }) { return <PageFrame kicker="THE PROJECT" title={<>A place imagined<br /><em>in conversation with land.</em></>} intro="Patagonia Underground is an early-stage project in Trevelin, Chubut, Argentina. Its purpose is to explore a future, low-profile accommodation experience that belongs to its landscape rather than competing with it."><div className="editorial-grid"><div><h3>Why Trevelin</h3><p>Trevelin brings together valley, forest, river and mountain conditions that make the relationship between nature and architecture especially meaningful.</p></div><div><h3>The architectural idea</h3><p>The current concept explores earth-sheltered forms, local material references, daylight and a central connection to the sky. Detailed design remains subject to planning and feasibility.</p></div><div><h3>Current status</h3><p><strong>Planning Stage.</strong> Construction has not been presented as started. Future phases will only be marked complete when there is a real update to share.</p></div></div><button className="arrow-link" onClick={() => navigate('/transparency')}>See project transparency <ArrowRight size={17} /></button></PageFrame> }
function StoryPage() { return <PageFrame kicker="OUR STORY" title={<>From an idea<br /><em>to a shared journey.</em></>} intro="This story is deliberately unfinished. The project is being shaped in public, with room for the place, the practical work and the truth of the process to change it."><StoryList /><div className="editorial-grid story-sections"><div><h3>The Idea</h3><p>A question about how a future retreat could feel embedded in the landscape rather than placed on top of it.</p></div><div><h3>Why Patagonia?</h3><p>Trevelin is the geographic and emotional reference point: green valleys, Andean weather, forests, rivers and a slower sense of scale.</p></div><div><h3>The Vision</h3><p>Warm, quiet and connected to the sky. A future experience shaped by stone, earth, timber and respect for what is already there.</p></div><div><h3>Building in Public</h3><p>We will share progress, uncertainty and milestones as they happen. No invented numbers, no staged construction updates.</p></div></div></PageFrame> }
function TransparencyBlock({ navigate }: { navigate: (to: string) => void }) { return <section className="progress section-pad"><SectionLabel number="04" text="Project transparency" /><div className="progress-head"><div><h2>Follow the<br /><em>real journey.</em></h2></div><div><p className="lead">Current stage: <strong>Planning Stage</strong></p><p>There is no construction progress to report yet. We will never replace a real update with a made-up percentage.</p><button className="arrow-link" onClick={() => navigate('/transparency')}>Open transparency <ArrowRight size={17} /></button></div></div><Timeline /></section> }
function Timeline() { return <div className="timeline">{phases.map(([number, title, description, status]) => <div className={`phase ${status}`} key={title}><span className="phase-number">{number}</span><div className="phase-dot" /><h3>{title}</h3><p>{description}</p><small>{status === 'complete' ? 'COMPLETE' : status === 'current' ? 'CURRENT' : status === 'next' ? 'NEXT' : 'FUTURE'}</small></div>)}</div> }
function TransparencyPage({ navigate }: { navigate: (to: string) => void }) { return <PageFrame kicker="PROJECT TRANSPARENCY" title={<>Show the work.<br /><em>When there is work.</em></>} intro="Transparency is part of the project, not a marketing layer. The current verified stage is Planning. No construction phase is marked complete."><Timeline /><div className="transparency-note"><h3>Financial transparency</h3><p>Project financial information will be shared progressively as the project develops. No budget figures are published at this stage.</p></div><button className="arrow-link" onClick={() => navigate('/journal')}>Open the journal <ArrowRight size={17} /></button></PageFrame> }
function ProgressPage() { return <PageFrame kicker="FOLLOW THE JOURNEY" title={<>Every phase.<br /><em>No invented progress.</em></>} intro="This is the project roadmap: a living view of what has happened, what is current and what remains ahead. Only verified milestones will move forward."><Timeline /><div className="transparency-note"><h3>Current verified phase: Planning</h3><p>There is no percentage score because construction has not started. Dates, evidence and phase notes will be added as the project develops.</p></div></PageFrame> }
function JournalPage() { return <PageFrame kicker="CONSTRUCTION JOURNAL" title={<>The journal will<br /><em>begin on site.</em></>} intro="The construction journal will begin when the first phase of the project starts."><div className="empty-state"><Mountain size={34} /><h3>No construction updates yet</h3><p>There are no real construction updates to publish at this stage. This space is ready for dated text, photography, video and phase information when available.</p></div></PageFrame> }
function GalleryPage() { return <PageFrame kicker="GALLERY" title={<>Trevelin first.<br /><em>Project, later.</em></>} intro="Explore the visual character of Trevelin through clearly labelled editorial references. Project photography will be added only when original or properly licensed assets are available."><div className="gallery-grid full-gallery"><figure className="large"><img src={images.forest} alt="Patagonian forest editorial reference" loading="lazy" /><figcaption>FOREST / TREVELIN REFERENCE</figcaption><small>{imageNote}</small></figure><figure><img src={images.lake} alt="Mountain lake editorial reference" loading="lazy" /><figcaption>WATER / TREVELIN REFERENCE</figcaption><small>{imageNote}</small></figure><figure><img src={images.valley} alt="Patagonian valley editorial reference" loading="lazy" /><figcaption>VALLEY / TREVELIN REFERENCE</figcaption><small>{imageNote}</small></figure><div className="gallery-note"><Camera size={22} /><p>Project category: awaiting original or licensed imagery. Concept visualizations will always be labelled.</p></div></div></PageFrame> }
function LocationPage() { return <PageFrame kicker="TREVELIN · CHUBUT · PATAGONIA" title={<>A landscape with<br /><em>its own voice.</em></>} intro="Trevelin is the regional setting for Patagonia Underground. This page intentionally avoids invented coordinates, distances and travel promises until they are verified and ready to share."><div className="location-feature"><img src={images.hero} alt="Trevelin landscape editorial reference" loading="lazy" /><div><strong>Trevelin, Chubut</strong><span>Patagonia · Argentina</span></div></div><div className="editorial-grid"><div><h3>Nature</h3><p>Valleys, mountains, forests, rivers and changing weather form the natural vocabulary of the region.</p></div><div><h3>Local atmosphere</h3><p>The project draws from the quiet scale and seasonal light of Trevelin, not from a generic Patagonia template.</p></div><div><h3>Travel information</h3><p>Verified access information and a responsible map experience will be added when exact project details are ready to publish.</p></div></div></PageFrame> }
function UpdatesPage() { return <PageFrame kicker="PROJECT UPDATES" title={<>Nothing staged.<br /><em>Nothing invented.</em></>} intro="Future updates can include a title, date, image, video, description and social sharing. Until there is a real development, there is no update to publish."><div className="empty-state"><Send size={34} /><h3>The journey has not published its first update</h3><p>When there is a verified milestone, it will appear here with its date, phase and source context.</p></div></PageFrame> }
function PageFrame({ kicker, title, intro, children }: { kicker: string; title: ReactNode; intro: string; children: ReactNode }) { return <section className="inner-page section-pad"><SectionLabel number="·" text={kicker} /><h1 className="page-title">{title}</h1><p className="page-intro">{intro}</p><div className="page-content">{children}</div></section> }
function Community({ join, formMessage }: { join: (event: FormEvent<HTMLFormElement>) => void; formMessage: string }) { return <section className="community section-pad" id="community"><div className="community-inner"><div><SectionLabel number="08" text="Follow the journey" /><h2>Be here from<br /><em>the beginning.</em></h2><p>Follow the project from the beginning and be among the first to know when Patagonia Underground comes to life.</p><p className="demo-note">Community signup is currently a local demo. Connect a secure database and email provider before launch.</p></div><form onSubmit={join} className="join-form"><label>First name<input required maxLength={80} autoComplete="given-name" name="firstName" placeholder="Your first name" /></label><label>Email<input required maxLength={160} autoComplete="email" type="email" name="email" placeholder="you@example.com" /></label><label>Country <span>(optional)</span><input maxLength={80} autoComplete="country-name" name="country" placeholder="Where are you joining from?" /></label><label className="checkbox"><input required type="checkbox" name="consent" /><span>I agree to receive project updates and understand I can unsubscribe at any time.</span></label>{formMessage && <p className="form-message" role="status">{formMessage}</p>}<button className="button cream" type="submit">Join the journey <Send size={15} /></button></form></div></section> }
function NotFound({ navigate }: { navigate: (to: string) => void }) { return <PageFrame kicker="404" title={<>This path is<br /><em>not mapped yet.</em></>} intro="The page you requested does not exist."><button className="button cream" onClick={() => navigate('/')}>Return home <ArrowRight size={15} /></button></PageFrame> }
function Footer({ navigate, setAdminOpen }: { navigate: (to: string) => void; setAdminOpen: (value: boolean) => void }) { return <footer className="footer"><div className="footer-brand"><span>PATAGONIA</span><strong>UNDERGROUND</strong><p>A project taking shape in Trevelin.</p></div><div className="footer-links"><div><span>EXPLORE</span><button onClick={() => navigate('/project')}>The project</button><button onClick={() => navigate('/transparency')}>Transparency</button><button onClick={() => navigate('/gallery')}>Gallery</button><button onClick={() => navigate('/location')}>Location</button></div><div><span>FOLLOW THE JOURNEY</span><span className="social-disabled"><Camera size={16} /> Instagram — coming soon</span><span className="social-disabled"><Video size={16} /> YouTube — coming soon</span><span className="social-disabled"><Play size={14} /> TikTok — coming soon</span></div></div><div className="footer-bottom"><span>© 2026 PATAGONIA UNDERGROUND</span><button onClick={() => setAdminOpen(true)}>Local admin demo</button><span>SELL LESS · TELL MORE · SHOW THE REAL JOURNEY</span></div></footer> }
function Admin({ members, setMembers, close }: { members: Member[]; setMembers: (members: Member[]) => void; close: () => void }) { const [query, setQuery] = useState(''); const [country, setCountry] = useState(''); const filtered = useMemo(() => members.filter(m => (!query || `${m.firstName} ${m.email}`.toLowerCase().includes(query.toLowerCase())) && (!country || m.country === country)), [members, query, country]); const countries = [...new Set(members.map(m => m.country).filter(Boolean))]; const exportCsv = () => { const csv = ['first_name,email,country,consent,created_at,status', ...members.map(m => [m.firstName, m.email, m.country, m.consent, m.createdAt, m.status].map(v => `"${String(v).replaceAll('"', '""')}"`).join(','))].join('\n'); const blob = new Blob([csv], { type: 'text/csv' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'patagonia-community.csv'; a.click(); URL.revokeObjectURL(url) }; const remove = (email: string) => { const next = members.filter(m => m.email !== email); saveMembers(next); setMembers(next) }; const toggle = (email: string) => { const next = members.map(m => m.email === email ? { ...m, status: m.status === 'active' ? 'inactive' as const : 'active' as const } : m); saveMembers(next); setMembers(next) }; return <div className="admin-overlay"><aside className="admin-drawer"><button className="admin-close" onClick={close} aria-label="Close admin"><X /></button><p className="eyebrow">LOCAL DEMO PANEL · NOT FOR PRODUCTION</p><h2>Community</h2><p>This browser stores {members.length} member{members.length === 1 ? '' : 's'}. Real authentication, database and email delivery are still required.</p><div className="admin-tools"><input placeholder="Search name or email" value={query} onChange={e => setQuery(e.target.value)} /><select value={country} onChange={e => setCountry(e.target.value)}><option value="">All countries</option>{countries.map(c => <option key={c}>{c}</option>)}</select><button className="button cream" onClick={exportCsv}><Download size={15} /> CSV export</button></div><div className="member-list">{filtered.map(member => <div className="member-row" key={member.email}><div><strong>{member.firstName}</strong><span>{member.email} · {member.country || 'Country not provided'}</span></div><small className={member.status}>{member.status}</small><button onClick={() => toggle(member.email)}>Toggle</button><button onClick={() => remove(member.email)}>Delete</button></div>)}{!filtered.length && <p>No local members yet.</p>}</div></aside></div> }
export default App
